version: '3'
services:
  # DB
  adminer:
    image: adminer:4.8.0
    network_mode: host
  db:
    image: postgres:13.2
    network_mode: host
    environment:
      POSTGRES_DB: fusionpbx
      POSTGRES_USER: fusionpbx
      POSTGRES_PASSWORD: fusionpbx
  # FusionPBX
  fusionpbx:
    image: fusionpbx:latest
    network_mode: host
    environment:
      DB_HOST: localhost
      DB_USER: fusionpbx
      DB_PASS: fusionpbx
